boxes/urls.py
#coding: utf-8

try:
    from django.conf.urls import *
except ImportError:  # django < 1.4
    from django.conf.urls.defaults import *

from .views import *

# place app url patterns here
urlpatterns = patterns('',
    url(r'^$', BoxList.as_view(), name='box_list'),

    url(r'^popular_boxes$', PopularBox.as_view(), name='popular_boxes'),
    url(r'^my_boxes$', UserBox.as_view(), name='my_boxes'),
    url(r'^search$', SearchBox.as_view(), name='search'),

    url(r'^new$', BoxCreate.as_view(), name='box_new'),
    url(r'^(?P<slug>\S{40})$', BoxView.as_view(), name='box_detail'),
    url(r'^(?P<slug>\S{40})/update$', BoxUpdate.as_view(), name='box_update'),
    url(r'^(?P<slug>\S{40})/delete$', BoxDelete.as_view(), name='box_delete'),

    url(r'^(?P<slug>\S{40})/addp$', AddParticipant, name='participant_add'),
    url(r'^(?P<slug>\S{40})/delp$', DelParticipant, name='participant_del'),
)

boxes/models.py
# coding: utf-8

from django.db.models import *
from django.utils.encoding import python_2_unicode_compatible
from easy_thumbnails.fields import ThumbnailerImageField


@python_2_unicode_compatible
class Box(Model):
    name = CharField("Event name", max_length=200)
    owner = ForeignKey(settings.AUTH_USER_MODEL, related_name="my_boxes", verbose_name='Owner')
    slug = CharField(max_length=40)
    location_long = FloatField()
    location_lat = FloatField()
    location_address = CharField(max_length=140)
    date_begin = DateTimeField()
    date_end = DateTimeField()
    description = TextField()
    RIGHTS = enumerate((
        'public',
        'private with invitation',
        'private with URL',
    ))
    rights = PositiveSmallIntegerField(choices=RIGHTS)
    participants = ManyToManyField(settings.AUTH_USER_MODEL, related_name="boxes")

    def __str__(self):
        return self.name

    @permalink
    def get_absolute_url(self):
        return 'box_detail', (self.pk,)

    @property
    def num_participants(self):
        return self.participants.count()

    @property
    def preview_pic(self):
        return self.pictures.order_by('?').first()

    def was_here(self, user):
        return self.participants.filter(pk=user.pk).exists()

class Picture(Model):
    box = ForeignKey(Box, related_name="pictures")
    owner = ForeignKey(settings.AUTH_USER_MODEL, related_name="pictures")
    picture = ThumbnailerImageField(upload_to='pictures/')

    def __str__(self):
        return "{0} by {1}".format(self.picture.name, self.owner.username)

boxes/forms.py
from django import forms

from .models import Box


class BoxForm(forms.ModelForm):


    RIGHTS = (
        (0, 'public'),
        (1, 'private with invitation'),
        (2, 'private with URL'),
    )

    location_long = forms.FloatField(widget=forms.HiddenInput)
    location_lat  = forms.FloatField(widget=forms.HiddenInput)
    location_address = forms.CharField(label="Address")
    description = forms.CharField(label="Description", required=False)
    date_begin = forms.DateTimeField(initial="12/12/2013 08:08")
    date_end = forms.DateTimeField(initial="13/12/2013 08:08")
    rights = forms.ChoiceField(
                    widget=forms.RadioSelect,
                    choices=RIGHTS,
                    initial=0,
            )

    class Meta:
        model = Box
        fields = [
            'name',
            'location_address',
            'date_begin',
            'date_end',
            'description',
            'rights',
            'location_lat',
            'location_long'

        ]

    def __init__(self, *args, **kwargs):
        super(BoxForm, self).__init__(*args, **kwargs)

        self.fields['date_begin'].label     = "Begin date"
        self.fields['date_end'].label       = "End date"
        self.fields['rights'].label         = "Box rights"

boxes/views.py
# Create your views here.
import hashlib
import random
import json

from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.templatetags.static import static
from django.views.generic import ListView, CreateView, UpdateView, \
                                 DeleteView, DetailView, TemplateView

from .models import *
from .forms import *

class JSONResponseMixin(object):
    """
    A mixin that can be used to render a JSON response.
    """
    def render_to_json_response(self, object, **response_kwargs):
        """
        Returns a JSON response, transforming 'context' to make the payload.
        """
        if 'values' in response_kwargs:
            values = response_kwargs['values']
            response_kwargs.pop('values')
        else:
            values = None

        return HttpResponse(
            self.convert_context_to_json(object, values),
            content_type='application/json',
            **response_kwargs
        )

    def convert_context_to_json(self, object, values):
        return json.dumps(list(object))


class UserLoggedMixin(object):
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(UserLoggedMixin, self).dispatch(request, *args, **kwargs)


class BoxList(UserLoggedMixin, TemplateView):
    template_name = 'boxes/box_list.html'


class BoxListJson(JSONResponseMixin, ListView):
    model = Box

    def render_to_response(self, context, **response_kwargs):
        qs = self.get_queryset()
        result =  [{
            'name': box.name,
            'slug': box.slug,
            'pic': box.preview_pic.picture.url if box.preview_pic
                                               else static('img/Partybox.png')
           } for box in qs]

        return self.render_to_json_response(result, **response_kwargs)


class PopularBox(BoxListJson):
    model = Box

    def get_queryset(self):
        qs = super(PopularBox, self).get_queryset()
        return qs.filter(rights=0)[:5]


class UserBox(UserLoggedMixin, BoxListJson):

    def get_queryset(self):
        qs = super(UserBox, self).get_queryset()
        return qs.filter(Q(owner=self.request.user) |
                         Q(participants=self.request.user))[:5]


class SearchBox(JSONResponseMixin, ListView):

    def get_queryset(self):
        q = self.request.GET['term']
        return Box.objects.filter(Q(name__icontains=q) |
                                  Q(description__icontains=q))

    def render_to_response(self, context, **response_kwargs):
        boxes = self.get_queryset()\
                    .extra(select={'value': 'name', 'url': 'slug'})\
                    .values('value', 'url')[:5]

        data = list(boxes)

        return HttpResponse(json.dumps(data), content_type='application/json',
                            **response_kwargs)


# TODO: Picture export
class BoxView(UserLoggedMixin, DetailView):
    model = Box

    def get_queryset(self):
        return super(BoxView, self).get_queryset().select_related()


# TODO: Display initial in forms
class BoxCreate(UserLoggedMixin, CreateView):
    model = Box
    form_class = BoxForm
    fields = [
        'name',
        'location_address',
        'date_begin',
        'date_end',
        'description',
        'rights',
        'location_lat',
        'location_long'
    ]

    def get_form_kwargs(self):
        form_kwargs = super(BoxCreate, self).get_form_kwargs()
        instance = Box(owner=self.request.user)
        instance.slug = hashlib.sha1(str(random.random()).encode('utf-8'))\
                                                         .hexdigest()
        form_kwargs['instance'] = instance

        return form_kwargs

    def form_valid(self, form):
        object = form.save()
        object.participants.add(object.owner)

        return super(BoxCreate, self).form_valid(form)
        

    @permalink
    def get_success_url(self):
        return 'box_detail', (self.object.slug,)


class BoxUpdate(UserLoggedMixin, UpdateView):
    model = Box
    form_class = BoxForm

    @permalink
    def get_success_url(self):
        return 'box_detail', (self.object.slug,)


class BoxDelete(UserLoggedMixin, DeleteView):
    model = Box

    def get_success_url(self):
        return reverse_lazy('box_list')


def AddParticipant(request, slug):
    box = Box.objects.filter(slug=slug).first()
    box.participants.add(request.user)

    return HttpResponseRedirect(reverse_lazy('box_detail', args=(slug,)))

def DelParticipant(request, slug):
    box = Box.objects.filter(slug=slug).first()
    box.participants.remove(request.user)

    return HttpResponseRedirect(reverse_lazy('box_detail', args=(slug,)))

boxes/templates/boxes/box_ajax_list.html
$.getJSON("{{ url }}", function( data ) {

	var htmlTab = []

	{% if title %}
		htmlTab.push('<h1>{{title}}</h1>')
	{% endif %}

    if(data == null || data == undefined || data.length == 0){
        htmlTab.push('<b>No box in this category</b>')
    } else {
        $.each( data, function( key, val ) {
            url = '/box/' + val['slug']
            html = '<div class="box-preview media">'

            if (val['pic'])
                html += '<a class="pull-right" href="' + url + '">' +
                            '<img class="media-object" src="' + val['pic'] + '" height="50px" alt="image"/>' +
                        '</a>'

            html += '<div class="media-body">' +
                        '<a href="' + url + '">' + val['name'] + '</a>' +
                    '</div>' +
                '</div>'

            htmlTab.push(html)
        });
    }
	$("#{{ id }}").html( htmlTab.join('') )
});

boxes/templates/boxes/box_confirm_delete.html
<form action="{% url 'box_delete' box_slug %}" method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-primary">Confirmer l'effacement</button>
</form>

boxes/templates/boxes/box_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load thumbnail %}
{% load box_filters %}

{% block extra_head %}
    <link href="{% static 'css/dropzone.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="//blueimp.github.io/Gallery/css/blueimp-gallery.min.css" />
{% endblock %}

{% block content %}

<div class="container">
	<div class="row">
  		<div class="col-md-9">
            <h1>{{ box.name }}</h1>


                {% if box.pictures.exists %}
					{% for picture in box.pictures.all %}
                        <a href="{{ picture.picture.url }}" data-gallery>
                            <img src="{{ picture.picture|thumbnail_url:'boxThumbs' }}" alt="{{ picture.picture.name }}" />
                        </a>
					{% endfor %}

				{% else %}
				<div class="col-md-12" style="padding:5px 5px 0px 0px;">
					<div class="alert alert-info"><strong>Hey!</strong> Cette boite est actuellement vide, déposez vos photos ;)</div>
				</div>
				{% endif %}
        </div>

  		<div class="col-md-3" style="padding:5px 0px">
            {%  if box.description %}
            <div class="well well-sm" id="description">
                <h4>Description:</h4>
  			    <i style="text-align:justify">{{ box.description }}</i>
            </div>
            {% endif %}

            <div>

                {% if box|was_here:user %}
                    <a href="{% url 'participant_del' box.slug %}" type="button" class="btn btn-primary btn-block">
                        Dire que je n'y était pas
                    </a>
                    <a href="#" type="button" class="btn btn-success btn-block" data-toggle="modal" data-target=".modal-upload">Ajouter une photo</a>
                    <a href="#" type="button" class="btn btn-success btn-block">Exporter Photos</a>
                {% else %}
                    <a href="{% url 'participant_add' box.slug %}" type="button" class="btn btn-primary btn-block">
                        Dire que j'y étais
                    </a>
                {% endif %}
                {% ifequal box.owner user %}
                        <a href="{% url 'box_update' slug=box.slug %}" type=button" class="btn btn-danger btn-block">Modifier Boite</a>
                        <a href="#" type="button" class="btn btn-danger btn-block" data-toggle="modal" data-target=".modal-delete">Supprimer la boite</a>
                {% endifequal %}


            </div>

			<div style="margin-top:5px; border-radius:5px">
				<div id="map-canvas" style="width:100%;height:400px;"></div>
			</div>
  		</div>
	</div>
</div>

<div class="modal fade modal-upload" tabindex="-1" role="dialog" aria-labelledby="uploadModal" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="uploadModal">Ajout de photos</h4>
        </div>
        <div class="modal-body">
            {% include "upload/index.html" with box_id=box.id %}
        </div>
    </div>
  </div>
</div>

<div class="modal fade modal-delete" tabindex="-1" role="dialog" aria-labelledby="deleteModal" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="deleteModal">Suppression de boite</h4>
      </div>
      <div class="modal-body">
        {% include "boxes/box_confirm_delete.html" with box_slug=box.slug %}
      </div>
    </div>
  </div>
</div>

<div id="blueimp-gallery" class="blueimp-gallery">
    <!-- The container for the modal slides -->
    <div class="slides"></div>
    <!-- Controls for the borderless lightbox -->
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
    <!-- The modal dialog, which will be used to wrap the lightbox content -->
    <div class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body next"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left prev">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                        Previous
                    </button>
                    <button type="button" class="btn btn-primary next">
                        Next
                        <i class="glyphicon glyphicon-chevron-right"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}


{% block js %}
		<script src="//maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
        <script src="//blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js"></script>
		<script type="text/javascript">
            function initialize() {

                var latLng = new google.maps.LatLng({{ box.location_lat|stringformat:"f" }}, {{ box.location_long|stringformat:"f" }});
                var mapOptions = {
                    zoom: 16,
                    center: latLng,
                    mapTypeId: google.maps.MapTypeId.HYBRID
                };

                map = new google.maps.Map(document.getElementById('map-canvas'),
                  mapOptions);

                var marker = new google.maps.Marker({
                    position: latLng,
                    map: map,
                });

            }

			google.maps.event.addDomListener(window, 'load', initialize);

		</script>
  {{ block.super }}
{% endblock %}

boxes/templates/boxes/box_form.html
{% extends "base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block content %}

 <div class="container">
     <div class="row">
         <div class="col-md-7">
            <h1>{% block boxForm_title %}{% endblock %}</h1>
            <form method="post" class="form-horizontal">
            {% csrf_token %}

            {% for input in form %}
                {% if input.is_hidden  %}
                    {{ input }}
                {% else %}
                    <div class="form-group {% if input.errors %}has-error{% endif %}">
                        <label for="id_{{ input.name }}" class="col-md-4 control-label">{{ input.label }}</label>

                        <div class="col-md-8">
                            {% if input.name != 'rights' %}
                                {% render_field input placeholder=input.label class+='form-control' %}
                            {% else %}
                                {% for choice in input.field.choices %}
                                    <div class="input-group" style="margin-bottom:15px">
                                        <span class="input-group-addon">
                                            <input type="radio" name="rights" value="{{choice.0}}" {% ifequal input.value choice.0 %}checked="checked"{% endifequal %}/>
                                        </span>

                                        <label for="id_{{ choice.name }}" class="form-control">{{ choice.1 }}</label>
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                {% endif %}

                {% if input.errors %}
                    <div class="form-group">
                        <div class="col-md-offset-4 col-md8">
                            <div class="alert alert-danger alert-dismissable">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                {{ input.errors }}
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}

            <div class="form-group">
                <div class="col-sm-offset-4 col-sm-8">
                    <input type="submit" value="Création de la  boite à souvenir" class="btn btn-success" />
                </div>
            </div>

            </form>
         </div>
         <div class="col-md-5">
            <div id="map"></div>
         </div>
     </div>
 </div>


{% endblock content %}

{% block js %}
    {{ block.super }}
    <script src="//maps.google.com/maps/api/js?sensor=false"></script>
    <script src="//raw.githubusercontent.com/aljeux/addresspicker/master/assets/jquery.ui.addresspicker.js"></script>

	<script>
        $(function() {
            var addresspickerMap = $("#id_location_address" ).addresspicker({
                regionBias: "fr",
                mapOptions: {
                    zoom: 16,
                    scrollwheel: true,
                    mapTypeId: google.maps.MapTypeId.HYBRID
                },
                elements: {
                    map: "#map",
                    lat: "#id_location_lat",
                    lng: "#id_location_long"
                }
            });

            var gmarker = addresspickerMap.addresspicker("marker");
            gmarker.setVisible(true);
            addresspickerMap.addresspicker("updatePosition");
        });
	</script>
{% endblock %}

boxes/templates/boxes/box_list.html
{% extends "base.html" %}
{% block content %}
	<div class="container" style="margin:15px">
		<div class="row">
			<div class="col-md-9">
				<div class="tab-content">
					<div class="tab-pane" id="my">Chargement en cours ...</div>
					<div class="tab-pane active" id="public">Chargement en cours ...</div>
				</div>
			</div>

 
			<div class="col-md-3 list-group" id="menu">
				<a class="list-group-item" href="{% url 'box_new' %}">Creer une boite</a>
				<!--<a class="list-group-item" href="#">Fil d'actualités</a>-->
				<a class="list-group-item" href="#my" data-toggle="tab">Mes boites</a>
				<a class="list-group-item" href="#public" data-toggle="tab">Boites publics</a>
			</div>
		</div>
	</div>
{% endblock content %}

{% block js %}
	{{ block.super }}
	<script>
		$('#menu a').click(function() {
		

			if ( $(this).attr('data-toggle') == 'tab') {

				$('.tab-pane').each(function(){

					$(this).removeClass('active')
				});

				$( $(this).attr('href') ).addClass('active')
			}
		})

		{% include "boxes/box_ajax_list.html" with url="/box/my_boxes" id="my" title="Mes boites de souvenirs" %}
		{% include "boxes/box_ajax_list.html" with url="/box/popular_boxes" id="public" title="Les boites de souvenirs public"%}
	</script>
{% endblock %}